from .keyboards import (
    language_keyboard,
    main_menu_keyboard,
    back_keyboard,
    game_result_keyboard,
    premium_keyboard,
    payment_method_keyboard,
    stars_payment_keyboard,
    admin_payment_keyboard,
    admin_main_keyboard,
    admin_support_ticket_keyboard,
    settings_keyboard,
    referral_keyboard,
    favorites_keyboard,
    bot_disable_confirm_keyboard,
    ai_chat_keyboard,
    upgrade_premium_keyboard,
)

__all__ = [
    "language_keyboard",
    "main_menu_keyboard",
    "back_keyboard",
    "game_result_keyboard",
    "premium_keyboard",
    "payment_method_keyboard",
    "stars_payment_keyboard",
    "admin_payment_keyboard",
    "admin_main_keyboard",
    "admin_support_ticket_keyboard",
    "settings_keyboard",
    "referral_keyboard",
    "favorites_keyboard",
    "bot_disable_confirm_keyboard",
    "ai_chat_keyboard",
    "upgrade_premium_keyboard",
]
